[build]
  command = "ng build --configuration production"
  publish = "dist/developercaseangular"

[[redirects]]
  from = "/api/*"
  to = "http://13.48.69.251:8081/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 